// Generated by Haxe 3.4.2
package hxDaedalus.data.graph;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Graph extends haxe.lang.HxObject
{
	static
	{
		//line 15 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		hxDaedalus.data.graph.Graph.INC = 0;
	}
	
	public Graph(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Graph()
	{
		//line 20 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		hxDaedalus.data.graph.Graph.__hx_ctor_hxDaedalus_data_graph_Graph(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_graph_Graph(hxDaedalus.data.graph.Graph __hx_this)
	{
		//line 21 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		__hx_this._id = hxDaedalus.data.graph.Graph.INC;
		//line 22 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		hxDaedalus.data.graph.Graph.INC++;
	}
	
	
	public static int INC;
	
	
	
	public int get_id()
	{
		//line 10 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		return this._id;
	}
	
	
	
	
	public hxDaedalus.data.graph.GraphEdge get_edge()
	{
		//line 12 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		return this._edge;
	}
	
	
	
	
	public hxDaedalus.data.graph.GraphNode get_node()
	{
		//line 14 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		return this._node;
	}
	
	
	public int _id;
	
	public hxDaedalus.data.graph.GraphNode _node;
	
	public hxDaedalus.data.graph.GraphEdge _edge;
	
	public void dispose()
	{
		//line 26 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		while (( this._node != null ))
		{
			//line 26 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			this.deleteNode(this._node);
		}
		
	}
	
	
	public hxDaedalus.data.graph.GraphNode insertNode()
	{
		//line 30 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		hxDaedalus.data.graph.GraphNode node = new hxDaedalus.data.graph.GraphNode();
		//line 31 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		if (( this._node != null )) 
		{
			//line 32 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			node.set_next(this._node);
			//line 33 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			this._node.set_prev(node);
		}
		
		//line 35 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		this._node = node;
		//line 36 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		return node;
	}
	
	
	public void deleteNode(hxDaedalus.data.graph.GraphNode node)
	{
		//line 40 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		while (( node.get_outgoingEdge() != null ))
		{
			//line 41 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (( node.get_outgoingEdge().get_oppositeEdge() != null )) 
			{
				//line 41 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				this.deleteEdge(node.get_outgoingEdge().get_oppositeEdge());
			}
			
			//line 42 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			this.deleteEdge(node.get_outgoingEdge());
		}
		
		//line 45 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		hxDaedalus.data.graph.GraphNode otherNode = this._node;
		//line 46 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		hxDaedalus.data.graph.GraphEdge incomingEdge = null;
		//line 47 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		while (( otherNode != null ))
		{
			//line 48 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			incomingEdge = ((hxDaedalus.data.graph.GraphEdge) (((haxe.ds.ObjectMap<hxDaedalus.data.graph.GraphNode, hxDaedalus.data.graph.GraphEdge>) (((haxe.IMap<hxDaedalus.data.graph.GraphNode, hxDaedalus.data.graph.GraphEdge>) (otherNode.get_successorNodes()) )) ).get(node)) );
			//line 49 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (( incomingEdge != null )) 
			{
				//line 49 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				this.deleteEdge(incomingEdge);
			}
			
			//line 50 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			otherNode = otherNode.get_next();
		}
		
		//line 53 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		if (( this._node == node )) 
		{
			//line 54 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (( node.get_next() != null )) 
			{
				//line 55 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				node.get_next().set_prev(null);
				//line 56 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				this._node = node.get_next();
			}
			else
			{
				//line 58 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				this._node = null;
			}
			
		}
		else
		{
			//line 61 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (( node.get_next() != null )) 
			{
				//line 62 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				node.get_prev().set_next(node.get_next());
				//line 63 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				node.get_next().set_prev(node.get_prev());
			}
			else
			{
				//line 65 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				node.get_prev().set_next(null);
			}
			
		}
		
		//line 69 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		node.dispose();
	}
	
	
	public hxDaedalus.data.graph.GraphEdge insertEdge(hxDaedalus.data.graph.GraphNode fromNode, hxDaedalus.data.graph.GraphNode toNode)
	{
		//line 73 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		if (( ((hxDaedalus.data.graph.GraphEdge) (((haxe.ds.ObjectMap<hxDaedalus.data.graph.GraphNode, hxDaedalus.data.graph.GraphEdge>) (((haxe.IMap<hxDaedalus.data.graph.GraphNode, hxDaedalus.data.graph.GraphEdge>) (fromNode.get_successorNodes()) )) ).get(toNode)) ) != null )) 
		{
			//line 73 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			return null;
		}
		
		//line 75 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		hxDaedalus.data.graph.GraphEdge edge = new hxDaedalus.data.graph.GraphEdge();
		//line 76 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		if (( this._edge != null )) 
		{
			//line 77 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			this._edge.set_prev(edge);
			//line 78 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			edge.set_next(this._edge);
		}
		
		//line 80 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		this._edge = edge;
		//line 82 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		edge.set_sourceNode(fromNode);
		//line 83 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		edge.set_destinationNode(toNode);
		//line 84 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		((haxe.ds.ObjectMap<hxDaedalus.data.graph.GraphNode, hxDaedalus.data.graph.GraphEdge>) (((haxe.IMap<hxDaedalus.data.graph.GraphNode, hxDaedalus.data.graph.GraphEdge>) (fromNode.get_successorNodes()) )) ).set(toNode, edge);
		//line 85 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		if (( fromNode.get_outgoingEdge() != null )) 
		{
			//line 86 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			fromNode.get_outgoingEdge().set_rotPrevEdge(edge);
			//line 87 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			edge.set_rotNextEdge(fromNode.get_outgoingEdge());
			//line 88 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			fromNode.set_outgoingEdge(edge);
		}
		else
		{
			//line 90 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			fromNode.set_outgoingEdge(edge);
		}
		
		//line 93 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		hxDaedalus.data.graph.GraphEdge oppositeEdge = ((hxDaedalus.data.graph.GraphEdge) (((haxe.ds.ObjectMap<hxDaedalus.data.graph.GraphNode, hxDaedalus.data.graph.GraphEdge>) (((haxe.IMap<hxDaedalus.data.graph.GraphNode, hxDaedalus.data.graph.GraphEdge>) (toNode.get_successorNodes()) )) ).get(fromNode)) );
		//line 94 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		if (( oppositeEdge != null )) 
		{
			//line 95 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			edge.set_oppositeEdge(oppositeEdge);
			//line 96 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			oppositeEdge.set_oppositeEdge(edge);
		}
		
		//line 99 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		return edge;
	}
	
	
	public void deleteEdge(hxDaedalus.data.graph.GraphEdge edge)
	{
		//line 103 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		if (( this._edge == edge )) 
		{
			//line 104 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (( edge.get_next() != null )) 
			{
				//line 105 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_next().set_prev(null);
				//line 106 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				this._edge = edge.get_next();
			}
			else
			{
				//line 108 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				this._edge = null;
			}
			
		}
		else
		{
			//line 111 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (( edge.get_next() != null )) 
			{
				//line 112 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_prev().set_next(edge.get_next());
				//line 113 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_next().set_prev(edge.get_prev());
			}
			else
			{
				//line 115 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_prev().set_next(null);
			}
			
		}
		
		//line 119 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		if (( edge.get_sourceNode().get_outgoingEdge() == edge )) 
		{
			//line 120 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (( edge.get_rotNextEdge() != null )) 
			{
				//line 121 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_rotNextEdge().set_rotPrevEdge(null);
				//line 122 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_sourceNode().set_outgoingEdge(edge.get_rotNextEdge());
			}
			else
			{
				//line 124 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_sourceNode().set_outgoingEdge(null);
			}
			
		}
		else
		{
			//line 127 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (( edge.get_rotNextEdge() != null )) 
			{
				//line 128 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_rotPrevEdge().set_rotNextEdge(edge.get_rotNextEdge());
				//line 129 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_rotNextEdge().set_rotPrevEdge(edge.get_rotPrevEdge());
			}
			else
			{
				//line 131 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				edge.get_rotPrevEdge().set_rotNextEdge(null);
			}
			
		}
		
		//line 134 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		edge.dispose();
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			switch (field.hashCode())
			{
				case 94650:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						this._id = ((int) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			switch (field.hashCode())
			{
				case 90842780:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("_edge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						this._edge = ((hxDaedalus.data.graph.GraphEdge) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 94650:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						this._id = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 91121377:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("_node")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						this._node = ((hxDaedalus.data.graph.GraphNode) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			switch (field.hashCode())
			{
				case 1764137480:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("deleteEdge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "deleteEdge")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 3355:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this.get_id();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 965713942:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("insertEdge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "insertEdge")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case -1249338716:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("get_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_id")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 1764416077:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("deleteNode")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "deleteNode")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 3108285:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("edge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this.get_edge();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 965992539:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("insertNode")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "insertNode")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 1976220934:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("get_edge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_edge")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 1671767583:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("dispose")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "dispose")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 3386882:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("node")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this.get_node();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 90842780:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("_edge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this._edge;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 1976499531:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("get_node")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_node")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 91121377:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("_node")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this._node;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 94650:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this._id;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			switch (field.hashCode())
			{
				case 94650:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((double) (this._id) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 3355:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return ((double) (this.get_id()) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			switch (field.hashCode())
			{
				case 1764137480:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("deleteEdge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						this.deleteEdge(((hxDaedalus.data.graph.GraphEdge) (dynargs.__get(0)) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case -1249338716:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("get_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this.get_id();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 965713942:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("insertEdge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this.insertEdge(((hxDaedalus.data.graph.GraphNode) (dynargs.__get(0)) ), ((hxDaedalus.data.graph.GraphNode) (dynargs.__get(1)) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 1976220934:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("get_edge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this.get_edge();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 1764416077:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("deleteNode")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						this.deleteNode(((hxDaedalus.data.graph.GraphNode) (dynargs.__get(0)) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 1976499531:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("get_node")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this.get_node();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 965992539:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("insertNode")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						return this.insertNode();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
				case 1671767583:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					if (field.equals("dispose")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
						this.dispose();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		baseArr.push("_edge");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		baseArr.push("_node");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		baseArr.push("_id");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		baseArr.push("node");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		baseArr.push("edge");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		baseArr.push("id");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/graph/Graph.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


