// Generated by Haxe 3.4.2
package hxPixels._Pixels;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class Pixels_Impl_
{
	static
	{
		//line 27 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.Pixels_Impl_.CHANNEL_MASK = 3;
	}
	
	public static int CHANNEL_MASK;
	
	public static hxPixels._Pixels.PixelsData _new(int width, int height, java.lang.Object alloc)
	{
		//line 33 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		boolean __temp_alloc27 = ( (haxe.lang.Runtime.eq(alloc, null)) ? (true) : (haxe.lang.Runtime.toBool(alloc)) );
		//line 33 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData this1 = new hxPixels._Pixels.PixelsData(width, height, __temp_alloc27, null);
		//line 33 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return ((hxPixels._Pixels.PixelsData) (this1) );
	}
	
	
	public static int getByte(hxPixels._Pixels.PixelsData this1, int i)
	{
		//line 41 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return ( this1.bytes.b[((int) (( (( i & -4 )) + ((int) (haxe.lang.Runtime.toInt(this1.format.channelMap.__get(( i & 3 )))) ) )) )] & 255 );
	}
	
	
	public static int getPixel(hxPixels._Pixels.PixelsData this1, int x, int y)
	{
		//line 46 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int pos = ( ( ( y * this1.width ) + x ) << 2 );
		//line 48 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int r = ( (( this1.bytes.b[( pos + this1.format.ch1 )] & 255 )) << 16 );
		//line 49 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int g = ( (( this1.bytes.b[( pos + this1.format.ch2 )] & 255 )) << 8 );
		//line 50 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int b = ( this1.bytes.b[( pos + this1.format.ch3 )] & 255 );
		//line 52 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return ((int) (( ( r | g ) | b )) );
	}
	
	
	public static int getPixel32(hxPixels._Pixels.PixelsData this1, int x, int y)
	{
		//line 57 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int pos = ( ( ( y * this1.width ) + x ) << 2 );
		//line 59 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int a = ( (( this1.bytes.b[( pos + this1.format.ch0 )] & 255 )) << 24 );
		//line 60 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int r = ( (( this1.bytes.b[( pos + this1.format.ch1 )] & 255 )) << 16 );
		//line 61 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int g = ( (( this1.bytes.b[( pos + this1.format.ch2 )] & 255 )) << 8 );
		//line 62 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int b = ( this1.bytes.b[( pos + this1.format.ch3 )] & 255 );
		//line 64 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return ((int) (( ( ( a | r ) | g ) | b )) );
	}
	
	
	public static void setByte(hxPixels._Pixels.PixelsData this1, int i, int value)
	{
		//line 70 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		this1.bytes.b[((int) (( (( i & -4 )) + ((int) (haxe.lang.Runtime.toInt(this1.format.channelMap.__get(( i & 3 )))) ) )) )] = ((byte) (value) );
	}
	
	
	public static void setPixel(hxPixels._Pixels.PixelsData this1, int x, int y, int value)
	{
		//line 75 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int pos = ( ( ( y * this1.width ) + x ) << 2 );
		//line 77 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int r = ( ( value >> 16 ) & 255 );
		//line 78 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int g = ( ( value >> 8 ) & 255 );
		//line 79 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int b = ( value & 255 );
		//line 81 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		this1.bytes.b[( pos + this1.format.ch1 )] = ((byte) (r) );
		//line 82 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		this1.bytes.b[( pos + this1.format.ch2 )] = ((byte) (g) );
		//line 83 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		this1.bytes.b[( pos + this1.format.ch3 )] = ((byte) (b) );
	}
	
	
	public static void setPixel32(hxPixels._Pixels.PixelsData this1, int x, int y, int value)
	{
		//line 88 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int pos = ( ( ( y * this1.width ) + x ) << 2 );
		//line 90 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int a = ( ( value >> 24 ) & 255 );
		//line 91 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int r = ( ( value >> 16 ) & 255 );
		//line 92 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int g = ( ( value >> 8 ) & 255 );
		//line 93 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int b = ( value & 255 );
		//line 95 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		this1.bytes.b[( pos + this1.format.ch0 )] = ((byte) (a) );
		//line 96 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		this1.bytes.b[( pos + this1.format.ch1 )] = ((byte) (r) );
		//line 97 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		this1.bytes.b[( pos + this1.format.ch2 )] = ((byte) (g) );
		//line 98 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		this1.bytes.b[( pos + this1.format.ch3 )] = ((byte) (b) );
	}
	
	
	public static void fillRect(hxPixels._Pixels.PixelsData this1, int x, int y, int width, int height, int value)
	{
		//line 103 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int pos = ( ( ( y * this1.width ) + x ) << 2 );
		//line 105 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData this2 = new hxPixels._Pixels.PixelsData(width, 1, true, null);
		//line 105 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData stridePixels = ((hxPixels._Pixels.PixelsData) (this2) );
		//line 106 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		stridePixels.format = this1.format;
		//line 107 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int stride = ( width << 2 );
		//line 109 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		{
			//line 109 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			int _g1 = 0;
			//line 109 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			int _g = width;
			//line 109 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			while (( _g1 < _g ))
			{
				//line 109 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int x1 = _g1++;
				//line 109 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				hxPixels._Pixels.Pixels_Impl_.setPixel32(stridePixels, x1, 0, value);
			}
			
		}
		
		//line 110 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		{
			//line 110 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			int _g11 = 0;
			//line 110 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			int _g2 = height;
			//line 110 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			while (( _g11 < _g2 ))
			{
				//line 110 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int y1 = _g11++;
				//line 111 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				this1.bytes.blit(pos, stridePixels.bytes, 0, stride);
				//line 112 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				pos += ( this1.width << 2 );
			}
			
		}
		
	}
	
	
	public static hxPixels._Pixels.PixelsData clone(hxPixels._Pixels.PixelsData this1)
	{
		//line 117 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData this2 = new hxPixels._Pixels.PixelsData(this1.width, this1.height, true, null);
		//line 117 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData clone = ((hxPixels._Pixels.PixelsData) (this2) );
		//line 118 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		clone.bytes.blit(0, this1.bytes, 0, this1.bytes.length);
		//line 119 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		clone.format = this1.format;
		//line 120 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return clone;
	}
	
	
	public static hxPixels._Pixels.PixelsData fromBytes(haxe.io.Bytes bytes, int width, int height, hxPixels.PixelFormat format)
	{
		//line 124 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData this1 = new hxPixels._Pixels.PixelsData(width, height, false, null);
		//line 124 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData pixels = ((hxPixels._Pixels.PixelsData) (this1) );
		//line 125 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		if (( format == null )) 
		{
			//line 125 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			format = hxPixels.PixelFormat.ARGB;
		}
		
		//line 126 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		pixels.bytes = bytes;
		//line 127 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return pixels;
	}
	
	
	public static hxPixels._Pixels.PixelsData convertTo(hxPixels._Pixels.PixelsData this1, hxPixels.PixelFormat format)
	{
		//line 131 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return hxPixels._Pixels.Pixels_Impl_.convert(((hxPixels._Pixels.PixelsData) (this1) ), format, true);
	}
	
	
	public static hxPixels._Pixels.PixelsData convert(hxPixels._Pixels.PixelsData pixels, hxPixels.PixelFormat toFormat, java.lang.Object inPlace)
	{
		//line 134 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		boolean __temp_inPlace28 = ( (haxe.lang.Runtime.eq(inPlace, null)) ? (false) : (haxe.lang.Runtime.toBool(inPlace)) );
		//line 135 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData res = ( (__temp_inPlace28) ? (pixels) : (hxPixels._Pixels.Pixels_Impl_.clone(pixels)) );
		//line 137 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		if (( toFormat == pixels.format )) 
		{
			//line 137 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			return res;
		}
		
		//line 139 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int i = 0;
		//line 140 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int pos = 0;
		//line 143 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		if (( ( ( pixels.format == hxPixels.PixelFormat.BGRA ) && ( toFormat == hxPixels.PixelFormat.RGBA ) ) || ( ( pixels.format == hxPixels.PixelFormat.RGBA ) && ( toFormat == hxPixels.PixelFormat.BGRA ) ) )) 
		{
			//line 146 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			while (( i < pixels.count ))
			{
				//line 148 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int i1 = ( pos + 1 );
				//line 148 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int r = ( ((hxPixels._Pixels.PixelsData) (pixels) ).bytes.b[((int) (( (( i1 & -4 )) + ((int) (haxe.lang.Runtime.toInt(((hxPixels._Pixels.PixelsData) (pixels) ).format.channelMap.__get(( i1 & 3 )))) ) )) )] & 255 );
				//line 149 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int i2 = ( pos + 3 );
				//line 149 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int b = ( ((hxPixels._Pixels.PixelsData) (pixels) ).bytes.b[((int) (( (( i2 & -4 )) + ((int) (haxe.lang.Runtime.toInt(((hxPixels._Pixels.PixelsData) (pixels) ).format.channelMap.__get(( i2 & 3 )))) ) )) )] & 255 );
				//line 151 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				res.bytes.b[( pos + toFormat.ch1 )] = ((byte) (r) );
				//line 152 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				res.bytes.b[( pos + toFormat.ch3 )] = ((byte) (b) );
				//line 154 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				 ++ i;
				//line 155 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				pos += 4;
			}
			
		}
		else
		{
			//line 158 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			while (( i < pixels.count ))
			{
				//line 160 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int a = ( ((hxPixels._Pixels.PixelsData) (pixels) ).bytes.b[((int) (( (( pos & -4 )) + ((int) (haxe.lang.Runtime.toInt(((hxPixels._Pixels.PixelsData) (pixels) ).format.channelMap.__get(( pos & 3 )))) ) )) )] & 255 );
				//line 161 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int i3 = ( pos + 1 );
				//line 161 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int r1 = ( ((hxPixels._Pixels.PixelsData) (pixels) ).bytes.b[((int) (( (( i3 & -4 )) + ((int) (haxe.lang.Runtime.toInt(((hxPixels._Pixels.PixelsData) (pixels) ).format.channelMap.__get(( i3 & 3 )))) ) )) )] & 255 );
				//line 162 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int i4 = ( pos + 2 );
				//line 162 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int g = ( ((hxPixels._Pixels.PixelsData) (pixels) ).bytes.b[((int) (( (( i4 & -4 )) + ((int) (haxe.lang.Runtime.toInt(((hxPixels._Pixels.PixelsData) (pixels) ).format.channelMap.__get(( i4 & 3 )))) ) )) )] & 255 );
				//line 163 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int i5 = ( pos + 3 );
				//line 163 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int b1 = ( ((hxPixels._Pixels.PixelsData) (pixels) ).bytes.b[((int) (( (( i5 & -4 )) + ((int) (haxe.lang.Runtime.toInt(((hxPixels._Pixels.PixelsData) (pixels) ).format.channelMap.__get(( i5 & 3 )))) ) )) )] & 255 );
				//line 165 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				res.bytes.b[( pos + toFormat.ch0 )] = ((byte) (a) );
				//line 166 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				res.bytes.b[( pos + toFormat.ch1 )] = ((byte) (r1) );
				//line 167 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				res.bytes.b[( pos + toFormat.ch2 )] = ((byte) (g) );
				//line 168 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				res.bytes.b[( pos + toFormat.ch3 )] = ((byte) (b1) );
				//line 170 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				 ++ i;
				//line 171 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				pos += 4;
			}
			
		}
		
		//line 175 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		res.format = toFormat;
		//line 176 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return res;
	}
	
	
	public static hxPixels._Pixels.PixelsData fromBufferedImage(java.awt.image.BufferedImage image)
	{
		//line 388 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData this1 = new hxPixels._Pixels.PixelsData(image.getWidth(), image.getHeight(), true, null);
		//line 388 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		hxPixels._Pixels.PixelsData pixels = ((hxPixels._Pixels.PixelsData) (this1) );
		//line 389 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		pixels.format = hxPixels.PixelFormat.RGBA;
		//line 391 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int[] buffer = new int[pixels.bytes.length];
		//line 392 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		buffer = image.getRaster().getPixels(((int) (0) ), ((int) (0) ), ((int) (pixels.width) ), ((int) (pixels.height) ), ((int[]) (buffer) ));
		//line 394 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		{
			//line 394 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			int _g1 = 0;
			//line 394 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			int _g = buffer.length;
			//line 394 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			while (( _g1 < _g ))
			{
				//line 394 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int i = _g1++;
				//line 394 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				pixels.bytes.b[i] = ((byte) (buffer[i]) );
			}
			
		}
		
		//line 396 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		return pixels;
	}
	
	
	public static void applyToBufferedImage(hxPixels._Pixels.PixelsData this1, java.awt.image.BufferedImage image)
	{
		//line 400 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		int[] buffer = new int[this1.bytes.length];
		//line 401 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		{
			//line 401 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			int _g1 = 0;
			//line 401 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			int _g = buffer.length;
			//line 401 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
			while (( _g1 < _g ))
			{
				//line 401 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				int i = _g1++;
				//line 401 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
				buffer[i] = ( this1.bytes.b[i] & 255 );
			}
			
		}
		
		//line 403 "/Users/tao/projects/hxDaedalus/src/hxPixels/Pixels.hx"
		image.getRaster().setPixels(((int) (0) ), ((int) (0) ), ((int) (this1.width) ), ((int) (this1.height) ), ((int[]) (buffer) ));
	}
	
	
}


