// Generated by Haxe 3.4.2
package hxDaedalus.iterators;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class FromVertexToNeighbourVertices extends haxe.lang.HxObject
{
	public FromVertexToNeighbourVertices(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public FromVertexToNeighbourVertices()
	{
		//line 12 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		hxDaedalus.iterators.FromVertexToNeighbourVertices.__hx_ctor_hxDaedalus_iterators_FromVertexToNeighbourVertices(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_iterators_FromVertexToNeighbourVertices(hxDaedalus.iterators.FromVertexToNeighbourVertices __hx_this)
	{
	}
	
	
	
	
	public hxDaedalus.data.Vertex _fromVertex;
	
	public hxDaedalus.data.Edge _nextEdge;
	
	public hxDaedalus.data.Vertex _resultVertex;
	
	public hxDaedalus.data.Vertex set_fromVertex(hxDaedalus.data.Vertex value)
	{
		//line 15 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		this._fromVertex = value;
		//line 16 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		this._nextEdge = this._fromVertex.get_edge();
		//line 17 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		return value;
	}
	
	
	public hxDaedalus.data.Vertex next()
	{
		//line 21 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		if (( this._nextEdge != null )) 
		{
			//line 22 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			this._resultVertex = this._nextEdge.get_oppositeEdge().get_originVertex();
			//line 23 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			while (true)
			{
				//line 24 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				this._nextEdge = this._nextEdge.get_rotLeftEdge();
				//line 23 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				if ( ! (( ! (this._nextEdge.get_isReal()) )) ) 
				{
					//line 23 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
			}
			
			//line 27 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			if (( this._nextEdge == this._fromVertex.get_edge() )) 
			{
				//line 27 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				this._nextEdge = null;
			}
			
		}
		else
		{
			//line 29 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			this._resultVertex = null;
		}
		
		//line 32 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		return this._resultVertex;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		{
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			switch (field.hashCode())
			{
				case -1844345344:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("_resultVertex")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						this._resultVertex = ((hxDaedalus.data.Vertex) (value) );
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return value;
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
				case -2064921106:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("fromVertex")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						this.set_fromVertex(((hxDaedalus.data.Vertex) (value) ));
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return value;
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
				case 1514466479:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("_nextEdge")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						this._nextEdge = ((hxDaedalus.data.Edge) (value) );
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return value;
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
				case -976608371:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("_fromVertex")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						this._fromVertex = ((hxDaedalus.data.Vertex) (value) );
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return value;
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
			}
			
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		{
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			switch (field.hashCode())
			{
				case 3377907:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("next")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "next")) );
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
				case -976608371:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("_fromVertex")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return this._fromVertex;
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
				case -761514517:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("set_fromVertex")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_fromVertex")) );
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
				case 1514466479:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("_nextEdge")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return this._nextEdge;
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
				case -1844345344:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("_resultVertex")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return this._resultVertex;
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
			}
			
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		{
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			boolean __temp_executeDef1 = true;
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			switch (field.hashCode())
			{
				case 3377907:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("next")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return this.next();
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
				case -761514517:
				{
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					if (field.equals("set_fromVertex")) 
					{
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						__temp_executeDef1 = false;
						//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
						return this.set_fromVertex(((hxDaedalus.data.Vertex) (dynargs.__get(0)) ));
					}
					
					//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
					break;
				}
				
				
			}
			
			//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
			if (__temp_executeDef1) 
			{
				//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		baseArr.push("_resultVertex");
		//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		baseArr.push("_nextEdge");
		//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		baseArr.push("_fromVertex");
		//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		baseArr.push("fromVertex");
		//line 6 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromVertexToNeighbourVertices.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


