// Generated by Haxe 3.4.2
package hxDaedalus.iterators;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class FromFaceToInnerVertices extends haxe.lang.HxObject
{
	public FromFaceToInnerVertices(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public FromFaceToInnerVertices()
	{
		//line 13 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		hxDaedalus.iterators.FromFaceToInnerVertices.__hx_ctor_hxDaedalus_iterators_FromFaceToInnerVertices(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_iterators_FromFaceToInnerVertices(hxDaedalus.iterators.FromFaceToInnerVertices __hx_this)
	{
	}
	
	
	
	
	public hxDaedalus.data.Face _fromFace;
	
	public hxDaedalus.data.Edge _nextEdge;
	
	public hxDaedalus.data.Vertex _resultVertex;
	
	public hxDaedalus.data.Face set_fromFace(hxDaedalus.data.Face value)
	{
		//line 16 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		this._fromFace = value;
		//line 17 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		this._nextEdge = this._fromFace.get_edge();
		//line 18 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		return value;
	}
	
	
	public hxDaedalus.data.Vertex next()
	{
		//line 22 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		if (( this._nextEdge != null )) 
		{
			//line 23 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			this._resultVertex = this._nextEdge.get_originVertex();
			//line 24 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			this._nextEdge = this._nextEdge.get_nextLeftEdge();
			//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			if (( this._nextEdge == this._fromFace.get_edge() )) 
			{
				//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
				this._nextEdge = null;
			}
			
		}
		else
		{
			//line 27 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			this._resultVertex = null;
		}
		
		//line 29 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		return this._resultVertex;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			switch (field.hashCode())
			{
				case -1844345344:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("_resultVertex")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						this._resultVertex = ((hxDaedalus.data.Vertex) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
				case -1245086425:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("fromFace")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						this.set_fromFace(((hxDaedalus.data.Face) (value) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
				case 1514466479:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("_nextEdge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						this._nextEdge = ((hxDaedalus.data.Edge) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
				case -1154568570:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("_fromFace")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						this._fromFace = ((hxDaedalus.data.Face) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			switch (field.hashCode())
			{
				case 3377907:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("next")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "next")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
				case -1154568570:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("_fromFace")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return this._fromFace;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
				case -1619148700:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("set_fromFace")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_fromFace")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
				case 1514466479:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("_nextEdge")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return this._nextEdge;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
				case -1844345344:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("_resultVertex")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return this._resultVertex;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			switch (field.hashCode())
			{
				case 3377907:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("next")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return this.next();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
				case -1619148700:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					if (field.equals("set_fromFace")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
						return this.set_fromFace(((hxDaedalus.data.Face) (dynargs.__get(0)) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		baseArr.push("_resultVertex");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		baseArr.push("_nextEdge");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		baseArr.push("_fromFace");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		baseArr.push("fromFace");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/iterators/FromFaceToInnerVertices.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


