// Generated by Haxe 3.4.2
package haxe.ds;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class StringMap<T> extends haxe.lang.HxObject implements haxe.IMap<java.lang.String, T>
{
	public StringMap(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public StringMap()
	{
		//line 59 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		haxe.ds.StringMap.__hx_ctor_haxe_ds_StringMap(((haxe.ds.StringMap<T>) (this) ));
	}
	
	
	public static <T_c> void __hx_ctor_haxe_ds_StringMap(haxe.ds.StringMap<T_c> __hx_this)
	{
		//line 61 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		__hx_this.cachedIndex = -1;
	}
	
	
	public int[] hashes;
	
	public java.lang.String[] _keys;
	
	public T[] vals;
	
	public int nBuckets;
	
	public int size;
	
	public int nOccupied;
	
	public int upperBound;
	
	public java.lang.String cachedKey;
	
	public int cachedIndex;
	
	public void set(java.lang.String key, T value)
	{
		//line 66 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		int x = 0;
		//line 66 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		int k = 0;
		//line 67 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		if (( this.nOccupied >= this.upperBound )) 
		{
			//line 69 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( this.nBuckets > ( this.size << 1 ) )) 
			{
				//line 70 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				this.resize(( this.nBuckets - 1 ));
			}
			else
			{
				//line 72 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				this.resize(( this.nBuckets + 2 ));
			}
			
		}
		
		//line 75 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		int[] hashes = this.hashes;
		//line 75 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		java.lang.String[] keys = this._keys;
		//line 75 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		int[] hashes1 = hashes;
		//line 76 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		{
			//line 77 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int mask = ( (( this.nBuckets == 0 )) ? (0) : (( this.nBuckets - 1 )) );
			//line 78 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			x = this.nBuckets;
			//line 78 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int site = x;
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int k1 = key.hashCode();
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k1 = ( ( k1 + 2127912214 ) + (( k1 << 12 )) );
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k1 = ( ( k1 ^ -949894596 ) ^ ( k1 >> 19 ) );
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k1 = ( ( k1 + 374761393 ) + (( k1 << 5 )) );
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k1 = ( ( k1 + -744332180 ) ^ ( k1 << 9 ) );
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k1 = ( ( k1 + -42973499 ) + (( k1 << 3 )) );
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k1 = ( ( k1 ^ -1252372727 ) ^ ( k1 >> 16 ) );
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int ret = k1;
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( (( ret & -2 )) == 0 )) 
			{
				//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				if (( ret == 0 )) 
				{
					//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					ret = 2;
				}
				else
				{
					//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					ret = -1;
				}
				
			}
			
			//line 79 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k = ret;
			//line 80 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int i = ( k & mask );
			//line 80 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int nProbes = 0;
			//line 82 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int delKey = -1;
			//line 84 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( hashes1[i] == 0 )) 
			{
				//line 85 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				x = i;
			}
			else
			{
				//line 88 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				int last = i;
				//line 88 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				int flag = 0;
				//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				while (true)
				{
					//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					boolean tmp = false;
					//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					flag = hashes1[i];
					//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (( flag != 0 )) 
					{
						//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						if (( flag == k )) 
						{
							//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							tmp = haxe.lang.Runtime.valEq(this._keys[i], key);
						}
						else
						{
							//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							tmp = false;
						}
						
					}
					else
					{
						//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						tmp = true;
					}
					
					//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if ( ! (( ! (tmp) )) ) 
					{
						//line 89 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						break;
					}
					
					//line 91 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (( ( flag == 1 ) && ( delKey == -1 ) )) 
					{
						//line 92 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						delKey = i;
					}
					
					//line 93 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					i = ( ( i +  ++ nProbes ) & mask );
				}
				
				//line 101 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				if (( ( flag == 0 ) && ( delKey != -1 ) )) 
				{
					//line 102 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					x = delKey;
				}
				else
				{
					//line 104 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					x = i;
				}
				
			}
			
		}
		
		//line 114 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		int flag1 = hashes1[x];
		//line 115 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		if (( flag1 == 0 )) 
		{
			//line 117 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			keys[x] = key;
			//line 118 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.vals[x] = value;
			//line 119 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			hashes1[x] = k;
			//line 120 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.size++;
			//line 121 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.nOccupied++;
		}
		else
		{
			//line 122 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( flag1 == 1 )) 
			{
				//line 123 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				keys[x] = key;
				//line 124 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				this.vals[x] = value;
				//line 125 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				hashes1[x] = k;
				//line 126 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				this.size++;
			}
			else
			{
				//line 128 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				boolean x1 = haxe.lang.Runtime.valEq(this._keys[x], key);
				//line 129 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				this.vals[x] = value;
			}
			
		}
		
		//line 132 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		this.cachedIndex = x;
		//line 133 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		this.cachedKey = key;
	}
	
	
	public int lookup(java.lang.String key)
	{
		//line 138 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		if (( this.nBuckets != 0 )) 
		{
			//line 140 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int[] hashes = this.hashes;
			//line 140 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			java.lang.String[] keys = this._keys;
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int mask = ( this.nBuckets - 1 );
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int k = key.hashCode();
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k = ( ( k + 2127912214 ) + (( k << 12 )) );
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k = ( ( k ^ -949894596 ) ^ ( k >> 19 ) );
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k = ( ( k + 374761393 ) + (( k << 5 )) );
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k = ( ( k + -744332180 ) ^ ( k << 9 ) );
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k = ( ( k + -42973499 ) + (( k << 3 )) );
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			k = ( ( k ^ -1252372727 ) ^ ( k >> 16 ) );
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int ret = k;
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( (( ret & -2 )) == 0 )) 
			{
				//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				if (( ret == 0 )) 
				{
					//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					ret = 2;
				}
				else
				{
					//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					ret = -1;
				}
				
			}
			
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int hash = ret;
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int k1 = hash;
			//line 142 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int nProbes = 0;
			//line 143 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int i = ( k1 & mask );
			//line 144 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int last = i;
			//line 144 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int flag = 0;
			//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			while (true)
			{
				//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				boolean tmp = false;
				//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				flag = hashes[i];
				//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				if (( flag != 0 )) 
				{
					//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if ( ! ((( ( flag == 1 ) || ( flag != k1 ) ))) ) 
					{
						//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						tmp =  ! (haxe.lang.Runtime.valEq(keys[i], key)) ;
					}
					else
					{
						//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						tmp = true;
					}
					
				}
				else
				{
					//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					tmp = false;
				}
				
				//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				if ( ! (tmp) ) 
				{
					//line 146 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				//line 148 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				i = ( ( i +  ++ nProbes ) & mask );
			}
			
			//line 161 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( (( flag & -2 )) == 0 )) 
			{
				//line 161 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				return -1;
			}
			else
			{
				//line 161 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				return i;
			}
			
		}
		
		//line 164 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		return -1;
	}
	
	
	public void resize(int newNBuckets)
	{
		//line 170 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		int[] newHash = null;
		//line 171 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		int j = 1;
		//line 172 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		{
			//line 173 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int x = newNBuckets;
			//line 173 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			 -- x;
			//line 173 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			x |= ( x >>> 1 );
			//line 173 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			x |= ( x >>> 2 );
			//line 173 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			x |= ( x >>> 4 );
			//line 173 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			x |= ( x >>> 8 );
			//line 173 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			x |= ( x >>> 16 );
			//line 173 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			newNBuckets =  ++ x;
			//line 174 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( newNBuckets < 4 )) 
			{
				//line 174 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				newNBuckets = 4;
			}
			
			//line 175 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( this.size >= ( ( newNBuckets * 0.77 ) + 0.5 ) )) 
			{
				//line 177 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				j = 0;
			}
			else
			{
				//line 179 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				int nfSize = newNBuckets;
				//line 180 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				newHash = new int[nfSize];
				//line 181 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				if (( this.nBuckets < newNBuckets )) 
				{
					//line 183 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					java.lang.String[] k = new java.lang.String[newNBuckets];
					//line 184 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (( this._keys != null )) 
					{
						//line 185 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						java.lang.System.arraycopy(((java.lang.Object) (this._keys) ), ((int) (0) ), ((java.lang.Object) (k) ), ((int) (0) ), ((int) (this.nBuckets) ));
					}
					
					//line 186 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					this._keys = k;
					//line 188 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					T[] v = ((T[]) (((java.lang.Object) (new java.lang.Object[newNBuckets]) )) );
					//line 189 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (( this.vals != null )) 
					{
						//line 190 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						java.lang.System.arraycopy(((java.lang.Object) (this.vals) ), ((int) (0) ), ((java.lang.Object) (v) ), ((int) (0) ), ((int) (this.nBuckets) ));
					}
					
					//line 191 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					this.vals = v;
				}
				
			}
			
		}
		
		//line 196 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		if (( j != 0 )) 
		{
			//line 199 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.cachedKey = null;
			//line 200 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.cachedIndex = -1;
			//line 202 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			j = -1;
			//line 203 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int nBuckets = this.nBuckets;
			//line 203 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			java.lang.String[] _keys = this._keys;
			//line 203 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			T[] vals = this.vals;
			//line 203 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int[] hashes = this.hashes;
			//line 205 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			int newMask = ( newNBuckets - 1 );
			//line 206 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			while ((  ++ j < nBuckets ))
			{
				//line 208 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				int k1 = hashes[j];
				//line 209 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				if (( (( k1 & -2 )) != 0 )) 
				{
					//line 211 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					java.lang.String key = _keys[j];
					//line 212 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					T val = vals[j];
					//line 214 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					hashes[j] = 1;
					//line 215 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					while (true)
					{
						//line 217 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						int nProbes = 0;
						//line 219 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						int i = ( k1 & newMask );
						//line 221 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						while (( newHash[i] != 0 ))
						{
							//line 222 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							i = ( ( i +  ++ nProbes ) & newMask );
						}
						
						//line 224 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						newHash[i] = k1;
						//line 226 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						boolean tmp = false;
						//line 226 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						if (( i < nBuckets )) 
						{
							//line 226 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							k1 = hashes[i];
							//line 226 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							tmp = ( (( k1 & -2 )) != 0 );
						}
						else
						{
							//line 226 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							tmp = false;
						}
						
						//line 226 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						if (tmp) 
						{
							//line 228 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							{
								//line 229 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
								java.lang.String tmp1 = _keys[i];
								//line 230 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
								_keys[i] = key;
								//line 231 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
								key = tmp1;
							}
							
							//line 233 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							{
								//line 234 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
								T tmp2 = vals[i];
								//line 235 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
								vals[i] = val;
								//line 236 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
								val = tmp2;
							}
							
							//line 239 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							hashes[i] = 1;
						}
						else
						{
							//line 241 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							_keys[i] = key;
							//line 242 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							vals[i] = val;
							//line 243 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
							break;
						}
						
					}
					
				}
				
			}
			
			//line 249 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (( nBuckets > newNBuckets )) 
			{
				//line 251 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				{
					//line 252 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					java.lang.String[] k2 = new java.lang.String[newNBuckets];
					//line 253 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					java.lang.System.arraycopy(((java.lang.Object) (_keys) ), ((int) (0) ), ((java.lang.Object) (k2) ), ((int) (0) ), ((int) (newNBuckets) ));
					//line 254 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					this._keys = k2;
				}
				
				//line 256 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				{
					//line 257 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					T[] v1 = ((T[]) (((java.lang.Object) (new java.lang.Object[newNBuckets]) )) );
					//line 258 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					java.lang.System.arraycopy(((java.lang.Object) (vals) ), ((int) (0) ), ((java.lang.Object) (v1) ), ((int) (0) ), ((int) (newNBuckets) ));
					//line 259 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					this.vals = v1;
				}
				
			}
			
			//line 263 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.hashes = newHash;
			//line 264 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.nBuckets = newNBuckets;
			//line 265 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.nOccupied = this.size;
			//line 266 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.upperBound = ((int) (( ( newNBuckets * 0.77 ) + .5 )) );
		}
		
	}
	
	
	public java.lang.Object get(java.lang.String key)
	{
		//line 272 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		int idx = -1;
		//line 273 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		boolean tmp = false;
		//line 273 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		if (haxe.lang.Runtime.valEq(this.cachedKey, key)) 
		{
			//line 273 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			idx = this.cachedIndex;
			//line 273 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			tmp = ( idx != -1 );
		}
		else
		{
			//line 273 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			tmp = false;
		}
		
		//line 273 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		if (tmp) 
		{
			//line 275 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			return this.vals[idx];
		}
		
		//line 278 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		idx = this.lookup(key);
		//line 279 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		if (( idx != -1 )) 
		{
			//line 281 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.cachedKey = key;
			//line 282 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			this.cachedIndex = idx;
			//line 284 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			return this.vals[idx];
		}
		
		//line 287 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		return null;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		{
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			switch (field.hashCode())
			{
				case 1005083856:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("cachedIndex")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.cachedIndex = ((int) (value) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 325636987:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("nBuckets")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.nBuckets = ((int) (value) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -1690761732:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("upperBound")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.upperBound = ((int) (value) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 3530753:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("size")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.size = ((int) (value) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -394102484:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("nOccupied")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.nOccupied = ((int) (value) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		{
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			switch (field.hashCode())
			{
				case 1005083856:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("cachedIndex")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.cachedIndex = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -1224424900:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("hashes")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.hashes = ((int[]) (value) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -553141795:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("cachedKey")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.cachedKey = haxe.lang.Runtime.toString(value);
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 91023059:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("_keys")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this._keys = ((java.lang.String[]) (value) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -1690761732:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("upperBound")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.upperBound = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 3612018:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("vals")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.vals = ((T[]) (value) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -394102484:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("nOccupied")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.nOccupied = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 325636987:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("nBuckets")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.nBuckets = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 3530753:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("size")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.size = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return value;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		{
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			switch (field.hashCode())
			{
				case 102230:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("get")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get")) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -1224424900:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("hashes")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.hashes;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -934437708:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("resize")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "resize")) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 91023059:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("_keys")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this._keys;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -1097094790:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("lookup")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "lookup")) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 3612018:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("vals")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.vals;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 113762:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("set")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set")) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 325636987:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("nBuckets")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.nBuckets;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 1005083856:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("cachedIndex")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.cachedIndex;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 3530753:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("size")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.size;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -553141795:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("cachedKey")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.cachedKey;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -394102484:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("nOccupied")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.nOccupied;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -1690761732:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("upperBound")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.upperBound;
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		{
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			switch (field.hashCode())
			{
				case 1005083856:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("cachedIndex")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((double) (this.cachedIndex) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 325636987:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("nBuckets")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((double) (this.nBuckets) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -1690761732:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("upperBound")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((double) (this.upperBound) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 3530753:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("size")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((double) (this.size) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -394102484:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("nOccupied")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return ((double) (this.nOccupied) );
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		{
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			boolean __temp_executeDef1 = true;
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			switch (field.hashCode())
			{
				case 102230:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("get")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.get(haxe.lang.Runtime.toString(dynargs.__get(0)));
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case 113762:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("set")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.set(haxe.lang.Runtime.toString(dynargs.__get(0)), ((T) (dynargs.__get(1)) ));
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -934437708:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("resize")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						this.resize(((int) (haxe.lang.Runtime.toInt(dynargs.__get(0))) ));
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
				case -1097094790:
				{
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					if (field.equals("lookup")) 
					{
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						__temp_executeDef1 = false;
						//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
						return this.lookup(haxe.lang.Runtime.toString(dynargs.__get(0)));
					}
					
					//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
					break;
				}
				
				
			}
			
			//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
			if (__temp_executeDef1) 
			{
				//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("cachedIndex");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("cachedKey");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("upperBound");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("nOccupied");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("size");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("nBuckets");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("vals");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("_keys");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		baseArr.push("hashes");
		//line 26 "/Users/tao/.hvm/versions/haxe/3.4.2/std/java/_std/haxe/ds/StringMap.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


