// Generated by Haxe 3.4.2
package hxDaedalus.data;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ConstraintShape extends haxe.lang.HxObject
{
	static
	{
		//line 8 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		hxDaedalus.data.ConstraintShape.INC = 0;
	}
	
	public ConstraintShape(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public ConstraintShape()
	{
		//line 11 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		hxDaedalus.data.ConstraintShape.__hx_ctor_hxDaedalus_data_ConstraintShape(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_ConstraintShape(hxDaedalus.data.ConstraintShape __hx_this)
	{
		//line 12 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		__hx_this._id = hxDaedalus.data.ConstraintShape.INC;
		//line 13 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		hxDaedalus.data.ConstraintShape.INC++;
		//line 14 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		__hx_this.segments = new haxe.root.Array<hxDaedalus.data.ConstraintSegment>();
	}
	
	
	public static int INC;
	
	
	
	public haxe.root.Array<hxDaedalus.data.ConstraintSegment> segments;
	
	public int _id;
	
	public int get_id()
	{
		//line 18 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		return this._id;
	}
	
	
	public void dispose()
	{
		//line 22 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		while (( this.segments.length > 0 ))
		{
			//line 22 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			((hxDaedalus.data.ConstraintSegment) (this.segments.pop()) ).dispose();
		}
		
		//line 23 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		this.segments = null;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		{
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			switch (field.hashCode())
			{
				case 94650:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("_id")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						this._id = ((int) (value) );
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return value;
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
			}
			
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		{
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			switch (field.hashCode())
			{
				case 94650:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("_id")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						this._id = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return value;
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
				case 1055868832:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("segments")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						this.segments = ((haxe.root.Array<hxDaedalus.data.ConstraintSegment>) (value) );
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return value;
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
			}
			
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		{
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			switch (field.hashCode())
			{
				case 1671767583:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("dispose")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "dispose")) );
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
				case 3355:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("id")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return this.get_id();
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
				case -1249338716:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("get_id")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_id")) );
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
				case 1055868832:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("segments")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return this.segments;
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
				case 94650:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("_id")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return this._id;
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
			}
			
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		{
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			switch (field.hashCode())
			{
				case 94650:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("_id")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return ((double) (this._id) );
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
				case 3355:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("id")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return ((double) (this.get_id()) );
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
			}
			
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		{
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			switch (field.hashCode())
			{
				case 1671767583:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("dispose")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						this.dispose();
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
				case -1249338716:
				{
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					if (field.equals("get_id")) 
					{
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						__temp_executeDef1 = false;
						//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
						return this.get_id();
					}
					
					//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
					break;
				}
				
				
			}
			
			//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		baseArr.push("_id");
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		baseArr.push("segments");
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		baseArr.push("id");
		//line 5 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/ConstraintShape.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


