// Generated by Haxe 3.4.2
package hxDaedalus.data;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Obstacle extends haxe.lang.HxObject
{
	static
	{
		//line 23 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		hxDaedalus.data.Obstacle.INC = 0;
	}
	
	public Obstacle(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Obstacle()
	{
		//line 41 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		hxDaedalus.data.Obstacle.__hx_ctor_hxDaedalus_data_Object(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_data_Object(hxDaedalus.data.Obstacle __hx_this)
	{
		//line 42 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._id = hxDaedalus.data.Obstacle.INC;
		//line 43 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		hxDaedalus.data.Obstacle.INC++;
		//line 45 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._pivotX = ((double) (0) );
		//line 46 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._pivotY = ((double) (0) );
		//line 48 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._matrix = new hxDaedalus.data.math.Matrix2D(null, null, null, null, null, null);
		//line 49 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._scaleX = ((double) (1) );
		//line 50 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._scaleY = ((double) (1) );
		//line 51 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._rotation = ((double) (0) );
		//line 52 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._x = ((double) (0) );
		//line 53 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._y = ((double) (0) );
		//line 55 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._coordinates = new haxe.root.Array<java.lang.Object>();
		//line 57 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		__hx_this._hasChanged = false;
	}
	
	
	public static int INC;
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	public int _id;
	
	public hxDaedalus.data.math.Matrix2D _matrix;
	
	public haxe.root.Array<java.lang.Object> _coordinates;
	
	public hxDaedalus.data.ConstraintShape _constraintShape;
	
	public double _pivotX;
	
	public double _pivotY;
	
	public double _scaleX;
	
	public double _scaleY;
	
	public double _rotation;
	
	public double _x;
	
	public double _y;
	
	public boolean _hasChanged;
	
	public int get_id()
	{
		//line 61 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._id;
	}
	
	
	public void dispose()
	{
		//line 65 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._matrix = null;
		//line 66 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._coordinates = null;
		//line 67 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._constraintShape = null;
	}
	
	
	public void updateValuesFromMatrix()
	{
	}
	
	
	public void updateMatrixFromValues()
	{
		//line 76 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._matrix.identity();
		//line 77 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._matrix.translate( - (this._pivotX) ,  - (this._pivotY) );
		//line 78 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._matrix.scale(this._scaleX, this._scaleY);
		//line 79 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._matrix.rotate(this._rotation);
		//line 80 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._matrix.translate(this._x, this._y);
	}
	
	
	public double get_pivotX()
	{
		//line 84 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._pivotX;
	}
	
	
	public double set_pivotX(double value)
	{
		//line 88 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._pivotX = value;
		//line 89 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._hasChanged = true;
		//line 90 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public double get_pivotY()
	{
		//line 94 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._pivotY;
	}
	
	
	public double set_pivotY(double value)
	{
		//line 98 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._pivotY = value;
		//line 99 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._hasChanged = true;
		//line 100 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public double get_scaleX()
	{
		//line 104 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._scaleX;
	}
	
	
	public double set_scaleX(double value)
	{
		//line 108 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		if (( this._scaleX != value )) 
		{
			//line 109 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._scaleX = value;
			//line 110 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._hasChanged = true;
		}
		
		//line 112 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public double get_scaleY()
	{
		//line 116 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._scaleY;
	}
	
	
	public double set_scaleY(double value)
	{
		//line 120 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		if (( this._scaleY != value )) 
		{
			//line 121 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._scaleY = value;
			//line 122 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._hasChanged = true;
		}
		
		//line 124 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public double get_rotation()
	{
		//line 128 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._rotation;
	}
	
	
	public double set_rotation(double value)
	{
		//line 132 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		if (( this._rotation != value )) 
		{
			//line 133 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._rotation = value;
			//line 134 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._hasChanged = true;
		}
		
		//line 136 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public double get_x()
	{
		//line 140 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._x;
	}
	
	
	public double set_x(double value)
	{
		//line 144 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		if (( this._x != value )) 
		{
			//line 145 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._x = value;
			//line 146 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._hasChanged = true;
		}
		
		//line 148 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public double get_y()
	{
		//line 152 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._y;
	}
	
	
	public double set_y(double value)
	{
		//line 156 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		if (( this._y != value )) 
		{
			//line 157 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._y = value;
			//line 158 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			this._hasChanged = true;
		}
		
		//line 160 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public hxDaedalus.data.math.Matrix2D get_matrix()
	{
		//line 164 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._matrix;
	}
	
	
	public hxDaedalus.data.math.Matrix2D set_matrix(hxDaedalus.data.math.Matrix2D value)
	{
		//line 168 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._matrix = value;
		//line 169 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._hasChanged = true;
		//line 170 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public haxe.root.Array<java.lang.Object> get_coordinates()
	{
		//line 174 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._coordinates;
	}
	
	
	public haxe.root.Array<java.lang.Object> set_coordinates(haxe.root.Array<java.lang.Object> value)
	{
		//line 178 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._coordinates = value;
		//line 179 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._hasChanged = true;
		//line 180 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public hxDaedalus.data.ConstraintShape get_constraintShape()
	{
		//line 185 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._constraintShape;
	}
	
	
	public hxDaedalus.data.ConstraintShape set_constraintShape(hxDaedalus.data.ConstraintShape value)
	{
		//line 189 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._constraintShape = value;
		//line 190 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._hasChanged = true;
		//line 191 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public boolean get_hasChanged()
	{
		//line 195 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return this._hasChanged;
	}
	
	
	public boolean set_hasChanged(boolean value)
	{
		//line 199 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		this._hasChanged = value;
		//line 200 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return value;
	}
	
	
	public haxe.root.Array<hxDaedalus.data.Edge> get_edges()
	{
		//line 205 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		haxe.root.Array<hxDaedalus.data.Edge> res = new haxe.root.Array<hxDaedalus.data.Edge>();
		//line 206 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		haxe.root.Array<hxDaedalus.data.ConstraintSegment> seg = this._constraintShape.segments;
		//line 207 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		{
			//line 207 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			int _g1 = 0;
			//line 207 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			int _g = seg.length;
			//line 207 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			while (( _g1 < _g ))
			{
				//line 207 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				int i = _g1++;
				//line 208 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				{
					//line 208 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					int _g3 = 0;
					//line 208 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					int _g2 = seg.__get(i).get_edges().length;
					//line 208 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					while (( _g3 < _g2 ))
					{
						//line 208 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						int j = _g3++;
						//line 209 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						res.push(seg.__get(i).get_edges().__get(j));
					}
					
				}
				
			}
			
		}
		
		//line 213 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return res;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			switch (field.hashCode())
			{
				case 3066:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._y = ((double) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -987906986:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_pivotX(value);
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 3065:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._x = ((double) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -987906985:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_pivotY(value);
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 50217181:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._rotation = ((double) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -908189618:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_scaleX(value);
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1800281454:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._scaleY = ((double) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -908189617:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_scaleY(value);
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1800281453:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._scaleX = ((double) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -40300674:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_rotation(value);
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1720564086:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._pivotY = ((double) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 120:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_x(value);
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1720564085:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._pivotX = ((double) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 121:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_y(value);
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 94650:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._id = ((int) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			switch (field.hashCode())
			{
				case -435323815:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_hasChanged")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._hasChanged = haxe.lang.Runtime.toBool(value);
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -987906986:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_pivotX(((double) (haxe.lang.Runtime.toDouble(value)) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 3066:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._y = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -987906985:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_pivotY(((double) (haxe.lang.Runtime.toDouble(value)) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 3065:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._x = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -908189618:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_scaleX(((double) (haxe.lang.Runtime.toDouble(value)) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 50217181:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._rotation = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -908189617:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_scaleY(((double) (haxe.lang.Runtime.toDouble(value)) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1800281454:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._scaleY = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -40300674:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_rotation(((double) (haxe.lang.Runtime.toDouble(value)) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1800281453:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._scaleX = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 120:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_x(((double) (haxe.lang.Runtime.toDouble(value)) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1720564086:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._pivotY = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 121:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_y(((double) (haxe.lang.Runtime.toDouble(value)) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1720564085:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._pivotX = ((double) (haxe.lang.Runtime.toDouble(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1081239615:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("matrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_matrix(((hxDaedalus.data.math.Matrix2D) (value) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -461323899:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_constraintShape")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._constraintShape = ((hxDaedalus.data.ConstraintShape) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1871919611:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("coordinates")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_coordinates(((haxe.root.Array<java.lang.Object>) (value) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1249876028:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_coordinates")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._coordinates = ((haxe.root.Array<java.lang.Object>) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 794782660:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("constraintShape")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_constraintShape(((hxDaedalus.data.ConstraintShape) (value) ));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1627231456:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_matrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._matrix = ((hxDaedalus.data.math.Matrix2D) (value) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1523636550:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("hasChanged")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.set_hasChanged(haxe.lang.Runtime.toBool(value));
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 94650:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this._id = ((int) (haxe.lang.Runtime.toInt(value)) );
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return value;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			switch (field.hashCode())
			{
				case 1133306925:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_edges")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_edges")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 3355:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_id();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -220229961:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_hasChanged")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_hasChanged")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -987906986:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_pivotX();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1551506243:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_hasChanged")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_hasChanged")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -987906985:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_pivotY();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1653701095:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_constraintShape")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_constraintShape")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -908189618:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_scaleX();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1097538341:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_constraintShape")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_constraintShape")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -908189617:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_scaleY();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -672149090:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_coordinates")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_coordinates")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -40300674:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_rotation();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1582901614:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_coordinates")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_coordinates")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 120:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_x();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1358723522:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_matrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_matrix")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 121:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_y();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 999438538:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_matrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_matrix")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1081239615:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("matrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_matrix();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 109328348:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_y")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1871919611:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("coordinates")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_coordinates();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 98246096:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_y")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 794782660:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("constraintShape")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_constraintShape();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 109328347:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_x")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1523636550:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("hasChanged")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_hasChanged();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 98246095:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_x")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 96356950:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("edges")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_edges();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -414362949:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_rotation")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 94650:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._id;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1963355577:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_rotation")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1627231456:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_matrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._matrix;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1185673524:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_scaleY")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1249876028:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_coordinates")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._coordinates;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1172488536:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_scaleY")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -461323899:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_constraintShape")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._constraintShape;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1185673525:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_scaleX")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1720564085:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._pivotX;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1172488535:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_scaleX")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1720564086:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._pivotY;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1265390892:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_pivotY")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1800281453:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._scaleX;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1092771168:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_pivotY")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1800281454:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._scaleY;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1265390893:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "set_pivotX")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 50217181:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._rotation;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1092771167:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_pivotX")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 3065:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._x;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1369572618:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("updateMatrixFromValues")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "updateMatrixFromValues")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 3066:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._y;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1115911606:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("updateValuesFromMatrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "updateValuesFromMatrix")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -435323815:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_hasChanged")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._hasChanged;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1671767583:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("dispose")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "dispose")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1249338716:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_id")) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			switch (field.hashCode())
			{
				case 3066:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._y;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 3355:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((double) (this.get_id()) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 3065:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._x;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -987906986:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_pivotX();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 50217181:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._rotation;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -987906985:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_pivotY();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1800281454:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._scaleY;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -908189618:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_scaleX();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1800281453:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._scaleX;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -908189617:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_scaleY();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1720564086:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._pivotY;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -40300674:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_rotation();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1720564085:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this._pivotX;
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 120:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_x();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 94650:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return ((double) (this._id) );
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 121:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_y();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, haxe.root.Array dynargs)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		{
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			boolean __temp_executeDef1 = true;
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			switch (field.hashCode())
			{
				case 1133306925:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_edges")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_edges();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1249338716:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_id")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_id();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -220229961:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_hasChanged")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_hasChanged(haxe.lang.Runtime.toBool(dynargs.__get(0)));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1671767583:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("dispose")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.dispose();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1551506243:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_hasChanged")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_hasChanged();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1115911606:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("updateValuesFromMatrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.updateValuesFromMatrix();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1653701095:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_constraintShape")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_constraintShape(((hxDaedalus.data.ConstraintShape) (dynargs.__get(0)) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1369572618:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("updateMatrixFromValues")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						this.updateMatrixFromValues();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1097538341:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_constraintShape")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_constraintShape();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1092771167:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_pivotX();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -672149090:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_coordinates")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_coordinates(((haxe.root.Array<java.lang.Object>) (dynargs.__get(0)) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1265390893:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_pivotX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_pivotX(((double) (haxe.lang.Runtime.toDouble(dynargs.__get(0))) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1582901614:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_coordinates")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_coordinates();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1092771168:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_pivotY();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1358723522:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_matrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_matrix(((hxDaedalus.data.math.Matrix2D) (dynargs.__get(0)) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1265390892:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_pivotY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_pivotY(((double) (haxe.lang.Runtime.toDouble(dynargs.__get(0))) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 999438538:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_matrix")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_matrix();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1172488535:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_scaleX();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 109328348:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_y(((double) (haxe.lang.Runtime.toDouble(dynargs.__get(0))) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1185673525:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_scaleX")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_scaleX(((double) (haxe.lang.Runtime.toDouble(dynargs.__get(0))) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 98246096:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_y")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_y();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 1172488536:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_scaleY();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 109328347:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_x(((double) (haxe.lang.Runtime.toDouble(dynargs.__get(0))) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1185673524:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_scaleY")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_scaleY(((double) (haxe.lang.Runtime.toDouble(dynargs.__get(0))) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case 98246095:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_x")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_x();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -1963355577:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("get_rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.get_rotation();
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
				case -414362949:
				{
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					if (field.equals("set_rotation")) 
					{
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						__temp_executeDef1 = false;
						//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
						return this.set_rotation(((double) (haxe.lang.Runtime.toDouble(dynargs.__get(0))) ));
					}
					
					//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
					break;
				}
				
				
			}
			
			//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
			if (__temp_executeDef1) 
			{
				//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_hasChanged");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_y");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_x");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_rotation");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_scaleY");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_scaleX");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_pivotY");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_pivotX");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_constraintShape");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_coordinates");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_matrix");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("_id");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("edges");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("hasChanged");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("constraintShape");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("coordinates");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("matrix");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("y");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("x");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("rotation");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("scaleY");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("scaleX");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("pivotY");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("pivotX");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		baseArr.push("id");
		//line 7 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/data/Object.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


