// Generated by Haxe 3.4.2
package hxDaedalus.factories;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class BitmapObject extends haxe.lang.HxObject
{
	public BitmapObject(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public BitmapObject()
	{
		//line 15 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		hxDaedalus.factories.BitmapObject.__hx_ctor_hxDaedalus_factories_BitmapObject(this);
	}
	
	
	public static void __hx_ctor_hxDaedalus_factories_BitmapObject(hxDaedalus.factories.BitmapObject __hx_this)
	{
	}
	
	
	public static hxDaedalus.data.Obstacle buildFromBmpData(hxPixels._Pixels.PixelsData bmpData, java.lang.Object simplificationEpsilon, hxPixels._Pixels.PixelsData debugBmp, wings.javaSwing.SimpleDrawingContext debugShape)
	{
		//line 21 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		double __temp_simplificationEpsilon22 = ( (haxe.lang.Runtime.eq(simplificationEpsilon, null)) ? (((double) (1) )) : (((double) (haxe.lang.Runtime.toDouble(simplificationEpsilon)) )) );
		//line 22 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		int i = 0;
		//line 23 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		int j = 0;
		//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		{
			//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			boolean cond = ( ( bmpData.width > 0 ) && ( bmpData.height > 0 ) );
			//line 25 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			java.lang.String message = ( ( ( ( "Invalid `bmpData` size (" + bmpData.width ) + ", " ) + bmpData.height ) + ")" );
		}
		
		//line 28 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		haxe.root.Array<haxe.root.Array<java.lang.Object>> shapes = hxDaedalus.data.math.Potrace.buildShapes(bmpData, debugBmp, debugShape);
		//line 31 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		if (( __temp_simplificationEpsilon22 >= 1 )) 
		{
			//line 32 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			int _g1 = 0;
			//line 32 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			int _g = shapes.length;
			//line 32 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			while (( _g1 < _g ))
			{
				//line 32 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				int i1 = _g1++;
				//line 33 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				shapes.__set(i1, hxDaedalus.data.math.ShapeSimplifier.simplify(shapes.__get(i1), __temp_simplificationEpsilon22));
			}
			
		}
		
		//line 38 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		haxe.root.Array<hxDaedalus.data.graph.Graph> graphs = new haxe.root.Array<hxDaedalus.data.graph.Graph>();
		//line 39 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		{
			//line 39 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			int _g11 = 0;
			//line 39 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			int _g2 = shapes.length;
			//line 39 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			while (( _g11 < _g2 ))
			{
				//line 39 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				int i2 = _g11++;
				//line 40 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				graphs.push(hxDaedalus.data.math.Potrace.buildGraph(shapes.__get(i2)));
			}
			
		}
		
		//line 44 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		haxe.root.Array<haxe.root.Array<java.lang.Object>> polygons = new haxe.root.Array<haxe.root.Array<java.lang.Object>>();
		//line 45 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		{
			//line 45 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			int _g12 = 0;
			//line 45 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			int _g3 = graphs.length;
			//line 45 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			while (( _g12 < _g3 ))
			{
				//line 45 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				int i3 = _g12++;
				//line 46 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				polygons.push(hxDaedalus.data.math.Potrace.buildPolygon(graphs.__get(i3), debugShape));
			}
			
		}
		
		//line 50 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		hxDaedalus.data.Obstacle obj = new hxDaedalus.data.Obstacle();
		//line 51 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		{
			//line 51 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			int _g13 = 0;
			//line 51 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			int _g4 = polygons.length;
			//line 51 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
			while (( _g13 < _g4 ))
			{
				//line 51 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				int i4 = _g13++;
				//line 52 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				j = 0;
				//line 53 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				while (( j < ( polygons.__get(i4).length - 2 ) ))
				{
					//line 55 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
					obj.get_coordinates().push(((double) (haxe.lang.Runtime.toDouble(polygons.__get(i4).__get(j))) ));
					//line 56 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
					obj.get_coordinates().push(((double) (haxe.lang.Runtime.toDouble(polygons.__get(i4).__get(( j + 1 )))) ));
					//line 57 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
					obj.get_coordinates().push(((double) (haxe.lang.Runtime.toDouble(polygons.__get(i4).__get(( j + 2 )))) ));
					//line 58 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
					obj.get_coordinates().push(((double) (haxe.lang.Runtime.toDouble(polygons.__get(i4).__get(( j + 3 )))) ));
					//line 59 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
					j += 2;
				}
				
				//line 61 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				obj.get_coordinates().push(((double) (haxe.lang.Runtime.toDouble(polygons.__get(i4).__get(0))) ));
				//line 62 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				obj.get_coordinates().push(((double) (haxe.lang.Runtime.toDouble(polygons.__get(i4).__get(1))) ));
				//line 63 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				obj.get_coordinates().push(((double) (haxe.lang.Runtime.toDouble(polygons.__get(i4).__get(j))) ));
				//line 64 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
				obj.get_coordinates().push(((double) (haxe.lang.Runtime.toDouble(polygons.__get(i4).__get(( j + 1 )))) ));
			}
			
		}
		
		//line 66 "/Users/tao/projects/hxDaedalus/src/hxDaedalus/factories/BitmapObject.hx"
		return obj;
	}
	
	
}


